---
name: disk-filler

releases:
- name: disk-filler
  version: 0.0.1
  url: git+https://github.com/s4heid/disk-filler-release.git

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: disk-filler
  azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: fill-disk
    release: disk-filler
    properties:
      size: 64M
  vm_type: default
  stemcell: default
  persistent_disk: 128
  networks:
  - name: default
